version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: autome-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: autome_dev
    volumes:
      - mongodb_data:/data/db
    networks:
      - autome-network

  redis:
    image: redis:7-alpine
    container_name: autome-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - autome-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: autome-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/autome_dev
      - DB_NAME=autome_dev
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis
    networks:
      - autome-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: autome-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - REACT_APP_ENVIRONMENT=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - autome-network

volumes:
  mongodb_data:
  redis_data:

networks:
  autome-network:
    driver: bridge